[package]
name = "partycat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
crossterm = "0.27.0"
hsv = "0.1.1"
termion = "2.0.1"
